# Board dimensions
BOARD_DIMENSION = 8

# Column indices
KING_START_COL = 4

QUEENSIDE_ROOK_COL = 0
QUEENSIDE_KING_DEST = 2
ROOK_QUEENSIDE_DEST = 3

ROOK_KINGSIDE_DEST = 5
KINGSIDE_KING_DEST = 6
KINGSIDE_ROOK_COL = 7

# Row indices
WHITE_HOME_ROW = 7
WHITE_PAWN_ROW = 6

BLACK_HOME_ROW = 0
BLACK_PAWN_ROW = 1

# Screen size
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
SQUARE_SIZE = 96
BOARD_SIZE = BOARD_DIMENSION * SQUARE_SIZE

# Renderer
PIECE_PADDING = 10
WIDGET_PADDING = 10
MOVE_RGB = (0, 255, 0)
CAPTURE_RGB = (255, 0, 0)
